FROM python:3.7-alpine

RUN apk update && apk add gcc libc-dev make git libffi-dev openssl-dev libxml2-dev libxslt-dev   python3-dev py3-setuptools jpeg-dev zlib-dev 
RUN adduser -D flask

WORKDIR /home/flask

COPY requirements.txt requirements.txt
RUN python -m venv venv
RUN venv/bin/pip install --upgrade pip
RUN venv/bin/pip install wheel
RUN venv/bin/pip install Pillow 
RUN venv/bin/pip3 install gunicorn

RUN venv/bin/pip3 install --no-cache-dir -r requirements.txt

COPY flaskblog flaskblog
COPY migrations migrations
COPY run.py flaskblog/config.py boot.sh ./
RUN chmod +x boot.sh

ENV FLASK_APP run.py

RUN chown -R flask:flask ./
USER flaskblog

EXPOSE 5000
ENTRYPOINT ["./boot.sh"]
